### ISSUE TITLE
plotExplanations produces graphs with Precision > 100%

### ISSUE THREAD

**Issue by thllwg** [viadee/anchorsOnR#65]
See example `mlr_bike.R`.  
In this example, the result for _case 476_ indicates a negative added precision for the feature weekday. 
```
====Explained Instance  476 ====
[removed]
====Result====
IF holiday = NO HOLIDAY (ADDED PRECISION: 18.32%, ADDED COVERAGE: 0%) AND
weathersit = GOOD (ADDED PRECISION: 4.49%, ADDED COVERAGE: -36%) AND
workingday = WORKING DAY (ADDED PRECISION: 0.85%, ADDED COVERAGE: -21%) AND
weekday IN {WED,THU,FRI} (ADDED PRECISION: -1.65%, ADDED COVERAGE: -16.8%)
THEN PREDICT 'above'
WITH PRECISION 100%, AND COVERAGE 26.2%
```

When plotted, plotExplanations() prints a corresponding message:

> Negative added precision is visualized as 0.

In fact, the resulting plot lacks the corresponding feature for _case 476_, but the remaining features add up to more than 100%.

![Rplot](https://user-images.githubusercontent.com/31413490/66270180-881adb80-e850-11e9-8166-a11ac3111122.png)

**Comment by TobiasGoerke** [comment]
@thllwg and I agreed on evenly distributing negative added precision values among the other features' values. This way no more graphs having total precision of over one are produced.
However, since we are considering the added features' precision as isolated values, we are disregarding possible feature interaction effects. Therefore, the user is to be warned via console output that the visualization might be misleading when dealing with negative precision values.
